### ISSUE TITLE
Missing information 

### ISSUE THREAD

**Issue by technophyte** [kckishan/HOGCN-LP#4] opened 2021-11-08 01:21 UTC
Thanks for sharing your code. While going through the repo, I found the readme for dataset description is unavailable. Please check.

**Comment by kckishan** [comment] 2021-11-09 13:58
Thanks for pointing it. I have updated the link to dataset description.

**Comment by kckishan** [comment] 2021-11-20 18:56
I hope the issue is resolved. Closing the issue.

**Closed by kckishan** 2021-11-20 18:56 UTC
